### ISSUE TITLE
Complete Postman Collection

### ISSUE THREAD

**Issue by GokceBaykan** [GRESB/api-docs#134]
Make a thorough check on the collection. Remove tests, verify names of the requests (and grouping), add more checkboxes. After identifying missing or incomplete indicators, add the requests. Complete tables, especially ones where naming conventions are unclear. If there is a clear naming convention to follow, include it in the documentation. Only whitelisted datapoints should be included in the collection.

**Comment by joeyhorst** [comment]
From feedback received they mostly want to be able to submit a response including all 3 components (Management, Performance, Development).

It wouldn't need to cover all data permutations, since we have shared a file with the variable names per indicator data field. What it should cover is an example of how things work per indicator. In other words submit some table answers, evidence, picklists per indicator to make it clear to the data partner user how to work with them.
