### ISSUE TITLE
Response delete - API

### ISSUE THREAD

**Issue by EmilTemirov** [GRESB/api-docs#16]
Could you please implement a delete operation for responses via API? Thanks.

**Comment by amichal** [comment]
Hi Emil,

Thanks for bringing this up.

We have so far specifically excluded DELETE from the public edit_assets API
since a response almost always contains content you are unable to
see/edit via the current API.

We anticipate that in most real world cases your user will already have a
response started with values entered for many areas not currently exposed
in the API. In this case you would want to list the existing response and
have your user select it. If they have not yet started their GRESB response
starting a new empty one for them does no harm so we allowed an API action
to setup a minimal response.

If we expose a delete method on the current API we have to choose to either:

* Allow the possibility that your 3rd party application can delete the work
of other users in the system. I don't think this is something we are
willing to do.

* Return a failure If there is *any* existing content other then the asset
level data you submitted.

If it's OK that in most real world cases the delete will fail then we can
allow newly created responses to be deleted (essentially an undo if a user
accidentally created a response and then through better of it).

**Comment by EmilTemirov** [comment]
API provides delete all asset data from response: http://gresb.github.io/api-docs/#show-asset-level-data
Therefore, if we will be able to delete empty "responses", then we can delete and not empty responses also by executing following commands sequentially:
```
DELETE /api/responses/:response_id/asset_level_data
```
```
DELETE /api/responses/:response_id  
```

**Comment by amichal** [comment]
Once a real user has started filling on the non-asset parts of a response
the second delete will be prevented. Does that make sense? The response is
a container for more then just the asset_level_data. As an example there
are answers to many other kinds of questions. Since we don't expose an API
to see/edit those parts exposing an API to delete a response would only
work in the case that a user has not manually entered ANY data for the
response in other areas.

All that said the API endpoint `DELETE /api/responses/:response_id` should
work on the sandbox but will soon almost always return an error once a real
user has started interacting with the survey. Once that logic is worked out
I'll add it to the API documentation.

**Comment by EmilTemirov** [comment]
Thanks! Now, I figured out what you mean. So, I think, DELETE action has no sense in API.
